@baseUrl = https://8080-otaviobonac-apiparap2ot-yazd3vissb3.ws-us114.gitpod.io

###
GET {{baseUrl}}/motoboys

###
POST {{baseUrl}}/motoboys
Content-Type: application/json

{
    "nome" : "Exemplo de Motoboy"
}

###
PUT {{baseUrl}}/motoboys/1
Content-Type: application/json

{
    "nome" : "Exemplo de Motoboy Alterado"
}

###
DELETE {{baseUrl}}/motoboys/1